[versions]
coroutines = "1.6.1"
kotlin = "1.7.0"

[libraries]
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

[plugins]
dokka = { id = "org.jetbrains.dokka", version = "1.7.0" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version = "3.10.0" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.20.0" }
